name: untitled12
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/my_gif.gif
    - assets/my_image.jpg
    - fonts/
  fonts:
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 100



